# Use an official Node.js runtime as a parent image
FROM node:bullseye AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . /app

# Use the start script to start the app
CMD ["npm", "start"]
