version: '3'
services:
  express-1:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/express
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
      - REDIS_HOST=redis
  express-2:
    build: .
    ports:
      - "3002:3000"
    volumes:
      - .:/express
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
      - REDIS_HOST=redis
  express-3:
    build: .
    ports:
      - "3003:3000"
    volumes:
      - .:/express
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
      - REDIS_HOST=redis

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_SKIP_NATIVE_AUTH=true
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express-1
      - express-2
      - express-3

volumes:
  db-data:

