FROM node:bullseye

WORKDIR /app

COPY . /app

RUN npm install
RUN npm install -g npm@9.6.5
EXPOSE 3000

CMD ["npm", "start"]

COPY ./db/schema.sql /docker-entrypoint-initdb.d/
COPY ./db/seeds.sql /docker-entrypoint-initdb.d/







